<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE person [
        <!ELEMENT person (name+,age?,sex*,school,birthday,city)>
        <!ELEMENT name (#PCDATA)>
        <!ATTLIST name
                ID3 ID #REQUIRED
        >
        <!ELEMENT age (#PCDATA)>
        <!ATTLIST age
                ID2 (AA|BB|CC) #REQUIRED
        >
        <!ELEMENT sex EMPTY>
        <!ELEMENT school ANY>
        <!ATTLIST school
                ID5 CDATA #FIXED  "ABC"
        >
        <!ELEMENT birthday ANY>

        <!ATTLIST birthday
                ID1 CDATA #IMPLIED
        >
        <!ELEMENT city (#PCDATA)>
        <!ENTITY testEntity "shenzheng">
        ]>

<person>
    <name ID3="A1">test</name>
    <name ID3="A2">test1</name>
    <age ID2="AA">20</age>
    <sex></sex>
    <school ID5="ABC">hainan</school>
    <birthday>1983</birthday>
    <city>&testEntity;</city>>
</person>